import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { IoMdAdd, IoMdClose, IoMdRemove } from "react-icons/io";
import { Link } from "react-router-dom";
import { useCart } from "../../../../Hooks/useCart";
export function CartItem({ item }) {
    const { removeCartItem, increaseAmount, decreaseAmount } = useCart();
    const { id, title, image, price, amount } = item;
    const subItemsTotal = (price * amount).toFixed(2);
    return (_jsx("div", { className: 'flex gap-x-4 py-2 lg:px-6 border-b border-gray-200 w-full font-light text-gray-500', children: _jsxs("div", { className: "w-full min-h-[150px] flex items-center gap-x-4", children: [_jsx(Link, { to: `/product/${id}`, children: _jsx("img", { className: 'max-w-[80px]', src: image, alt: '' }) }), _jsxs("div", { className: "w-full flex flex-col", children: [_jsxs("div", { className: "flex justify-between mb-2", children: [_jsx(Link, { to: `/product/${id}`, className: 'text-sm uppercase font-medium max-w-[240px] text-primary hover:underline', children: title }), _jsx("div", { onClick: () => removeCartItem(id), className: "text-xl cursor-pointer", children: _jsx(IoMdClose, { className: 'text-gray-500 hover:text-red-500 transition' }) })] }), _jsxs("div", { className: "flex gap-x-2 h-[36px] text-sm", children: [_jsxs("div", { className: "flex flex-1 max-w-[100px] items-center h-full border text-primary font-medium", children: [_jsx("div", { onClick: () => decreaseAmount(id), className: "flex-1 flex justify-center items-center cursor-pointer h-full", children: _jsx(IoMdRemove, {}) }), _jsx("div", { className: "h-full flex justify-center items-center px-2", children: amount }), _jsx("div", { onClick: () => increaseAmount(id), className: "flex-1 flex justify-center items-center cursor-pointer h-full", children: _jsx(IoMdAdd, {}) })] }), _jsxs("div", { className: "flex-1 flex items-center justify-around", children: ["$", price] }), _jsxs("div", { className: "flex-1 flex justify-end items-center text-primary font-medium", children: ["$", (subItemsTotal)] })] })] })] }) }));
}
